export default defineEventHandler((event) => {
  return [
    {
      number: 3,
      nkjv: "For I proclaim the name of the <em>Lord</em>: Ascribe greatness to our God.",
      esv: "For I will proclaim the name of the <em>Lord</em>; ascribe greatness to our God!",
      csb: "For I will proclaim the <em>Lord</em>'s name. Declare the greatness of our God!",
      net: "For I will proclaim the name of the <em>Lord</em>; you must acknowledge the greatness of our God.",
      nlt: "I will proclaim the name of the <em>Lord</em>; how glorious is our God!",
    },
    {
      number: 4,
      nkjv: "<i>He is</i> the Rock, His work <i>is</i> perfect; For all His ways <i>are</i> justice, A God of truth and without injustice; Righteous and upright <i>is</i> He.",
      esv: '"The Rock, his work is perfect, for all his ways are justice. A God of faithfulness and without iniquity, just and upright is he.',
      csb: "The Rock--his work is perfect; all his ways are just. A faithful God, without bias, he is righteous and true.",
      net: "As for the Rock, his work is perfect, for all his ways are just. He is a reliable God who is never unjust, he is fair and upright.",
      nlt: "He is the Rock; his deeds are perfect. Everything he does is just and fair. He is a faithful God who does no wrong; how just and upright he is!",
    },
    {
      number: 5,
      nkjv: '"They have corrupted themselves; <i>They are</i> not His children, Because of their blemish: A perverse and crooked generation.',
      esv: "They have dealt corruptly with him; they are no longer his children because they are blemished; they are a crooked and twisted generation.",
      csb: "His people have acted corruptly toward him; this is their defect--they are not his children but a devious and crooked generation.",
      net: "His people have been unfaithful to him; they have not acted like his children - this is their sin. They are a perverse and deceitful generation.",
      nlt: '"But they have acted corruptly toward him; when they act so perversely, are they really his children? They are a deceitful and twisted generation.',
    },
    {
      number: 6,
      nkjv: "Do you thus deal with the <em>Lord</em>, O foolish and unwise people? <i>Is</i> He not your Father, <i>who</i> bought you? Has He not made you and established you?",
      esv: "Do you thus repay the <em>Lord</em>, you foolish and senseless people? Is not he your father, who created you, who made you and established you?",
      csb: "Is this how you repay the <em>Lord</em>, you foolish and senseless people? Isn't he your Father and Creator? Didn't he make you and sustain you?",
      net: "Is this how you repay the <em>Lord</em>, you foolish, unwise people? Is he not your father, your creator? He has made you and established you.",
      nlt: "Is this the way you repay the <em>Lord</em>, you foolish and senseless people? Isn't he your Father who created you? Has he not made you and established you?",
    },
    {
      number: 10,
      nkjv: '"He found him in a desert land And in the wasteland, a howling wilderness; He encircled him, He instructed him, He kept him as the apple of His eye.',
      esv: '"He found him in a desert land, and in the howling waste of the wilderness; he encircled him, he cared for him, he kept him as the apple of his eye.',
      csb: "He found him in a desolate land, in a barren, howling wilderness; he surrounded him, cared for him, and protected him as the pupil of his eye.",
      net: "The <em>Lord</em> found him in a desolate land, in an empty wasteland where animals howl. He continually guarded him and taught him; he continually protected him like the pupil of his eye.",
      nlt: "He found them in a desert land, in an empty, howling wasteland. He surrounded them and watched over them; he guarded them as he would guard his own eyes.",
    },
    {
      number: 11,
      nkjv: "As an eagle stirs up its nest, Hovers over its young, Spreading out its wings, taking them up, Carrying them on its wings,",
      esv: "Like an eagle that stirs up its nest, that flutters over its young, spreading out its wings, catching them, bearing them on its pinions,",
      csb: "He watches over his nest like an eagle and hovers over his young; he spreads his wings, catches him, and carries him on his feathers.",
      net: "Like an eagle that stirs up its nest, that hovers over its young, so the <em>Lord</em> spread out his wings and took him, he lifted him up on his pinions.",
      nlt: "Like an eagle that rouses her chicks and hovers over her young, so he spread his wings to take them up and carried them safely on his pinions.",
    },
    {
      number: 12,
      nkjv: "<i>So</i> the <em>Lord</em> alone led him, And <i>there was</i> no foreign god with him.",
      esv: "the <em>Lord</em> alone guided him, no foreign god was with him.",
      csb: "The <em>Lord</em> alone led him, with no help from a foreign god.",
      net: "The <em>Lord</em> alone was guiding him, no foreign god was with him.",
      nlt: "The <em>Lord</em> alone guided them; they followed no foreign gods.",
    },
    {
      number: 13,
      nkjv: '"He made him ride in the heights of the earth, That he might eat the produce of the fields; He made him draw honey from the rock, And oil from the flinty rock;',
      esv: "He made him ride on the high places of the land, and he ate the produce of the field, and he suckled him with honey out of the rock, and oil out of the flinty rock.",
      csb: "He made him ride on the heights of the land and eat the produce of the field. He nourished him with honey from the rock and oil from flinty rock,",
      net: "He enabled him to travel over the high terrain of the land, and he ate of the produce of the fields. He provided honey for him from the cliffs, and olive oil from the hardest of rocks,",
      nlt: "He let them ride over the highlands and feast on the crops of the fields. He nourished them with honey from the rock and olive oil from the stony ground.",
    },
    {
      number: 14,
      nkjv: "Curds from the cattle, and milk of the flock, With fat of lambs; And rams of the breed of Bashan, and goats, With the choicest wheat; And you drank wine, the blood of the grapes.",
      esv: "Curds from the herd, and milk from the flock, with fat of lambs, rams of Bashan and goats, with the very finest of the wheat-- and you drank foaming wine made from the blood of the grape.",
      csb: "curds from the herd and milk from the flock, with the fat of lambs, rams from Bashan, and goats, with the choicest grains of wheat; you drank wine from the finest grapes.",
      net: "butter from the herd and milk from the flock, along with the fat of lambs, rams and goats of Bashan, along with the best of the kernels of wheat; and from the juice of grapes you drank wine.",
      nlt: "He fed them yogurt from the herd and milk from the flock, together with the fat of lambs. He gave them choice rams from Bashan, and goats, together with the choicest wheat. You drank the finest wine, made from the juice of grapes.",
    },
    {
      number: 18,
      nkjv: "Of the Rock <i>who</i> begot you, you are unmindful, And have forgotten the God who fathered you.",
      esv: "You were unmindful of the Rock that bore you, and you forgot the God who gave you birth.",
      csb: "You ignored the Rock who gave you birth; you forgot the God who gave birth to you.",
      net: "You have forgotten the Rock who fathered you, and put out of mind the God who gave you birth.",
      nlt: "You neglected the Rock who had fathered you; you forgot the God who had given you birth.",
    },
  ];
});
