export default defineEventHandler((event) => {
  return [
    {
      number: 1,
      nkjv: 'After these things the word of the LORD came to Abram in a vision, saying, "Do not be afraid, Abram. I <i>am</i> your shield, your exceedingly great reward."',
      esv: 'After these things the word of the LORD came to Abram in a vision: "Fear not, Abram, I am your shield; your reward shall be very great."',
      csb: "After these events, the word of the LORD came to Abram in a vision: Do not be afraid, Abram. I am your shield; your reward will be very great.",
      net: 'After these things the word of the LORD came to Abram in a vision: "Fear not, Abram! I am your shield and the one who will reward you in great abundance."',
      nlt: 'Some time later, the LORD spoke to Abram in a vision and said to him, "Do not be afraid, Abram, for I will protect you, and your reward will be great."',
    },
    {
      number: 2,
      nkjv: 'But Abram said, "Lord GOD, what will You give me, seeing I go childless, and the heir of my house <i>is</i> Eliezer of Damascus?"',
      esv: 'But Abram said, "O Lord GOD, what will you give me, for I continue childless, and the heir of my house is Eliezer of Damascus?"',
      csb: 'But Abram said, "Lord GOD, what can you give me, since I am childless and the heir of my house is Eliezer of Damascus?"',
      net: 'But Abram said, "O sovereign LORD, what will you give me since I continue to be childless, and my heir is Eliezer of Damascus?"',
      nlt: "But Abram replied, \"O Sovereign LORD, what good are all your blessings when I don't even have a son? Since you've given me no children, Eliezer of Damascus, a servant in my household, will inherit all my wealth.",
    },
    {
      number: 3,
      nkjv: 'Then Abram said, "Look, You have given me no offspring; indeed one born in my house is my heir!"',
      esv: 'And Abram said, "Behold, you have given me no offspring, and a member of my household will be my heir."',
      csb: 'Abram continued, "Look, you have given me no offspring, so a slave born in my house will be my heir."',
      net: 'Abram added, "Since you have not given me a descendant, then look, one born in my house will be my heir!"',
      nlt: 'You have given me no descendants of my own, so one of my servants will be my heir."',
    },
    {
      number: 4,
      nkjv: 'And behold, the word of the LORD <i>came</i> to him, saying, "This one shall not be your heir, but one who will come from your own body shall be your heir."',
      esv: 'And behold, the word of the LORD came to him: "This man shall not be your heir; your very own son shall be your heir."',
      csb: 'Now the word of the LORD came to him: "This one will not be your heir; instead, one who comes from your own body will be your heir."',
      net: 'But look, the word of the LORD came to him: "This man will not be your heir, but instead a son who comes from your own body will be your heir."',
      nlt: 'Then the LORD said to him, "No, your servant will not be your heir, for you will have a son of your own who will be your heir."',
    },
    {
      number: 5,
      nkjv: 'Then He brought him outside and said, "Look now toward heaven, and count the stars if you are able to number them." And He said to him, "So shall your descendants be."',
      esv: 'And he brought him outside and said, "Look toward heaven, and number the stars, if you are able to number them." Then he said to him, "So shall your offspring be."',
      csb: 'He took him outside and said, "Look at the sky and count the stars, if you are able to count them." Then he said to him, "Your offspring will be that numerous."',
      net: 'The LORD took him outside and said, "Gaze into the sky and count the stars - if you are able to count them!" Then he said to him, "So will your descendants be."',
      nlt: 'Then the LORD took Abram outside and said to him, "Look up into the sky and count the stars if you can. That\'s how many descendants you will have!"',
    },
    {
      number: 6,
      nkjv: "And he believed in the LORD, and He accounted it to him for righteousness.",
      esv: "And he believed the LORD, and he counted it to him as righteousness.",
      csb: "Abram believed the LORD, and he credited it to him as righteousness.",
      net: "Abram believed the LORD, and the LORD considered his response of faith as proof of genuine loyalty.",
      nlt: "And Abram believed the LORD, and the LORD counted him as righteous because of his faith.",
    },
    {
      number: 7,
      nkjv: 'Then He said to him, "I <i>am</i> the LORD, who brought you out of Ur of the Chaldeans, to give you this land to inherit it."',
      esv: 'And he said to him, "I am the LORD who brought you out from Ur of the Chaldeans to give you this land to possess."',
      csb: 'He also said to him, "I am the LORD who brought you from Ur of the Chaldeans to give you this land to possess."',
      net: 'The LORD said to him, "I am the LORD who brought you out from Ur of the Chaldeans to give you this land to possess."',
      nlt: 'Then the LORD told him, "I am the LORD who brought you out of Ur of the Chaldeans to give you this land as your possession."',
    },
  ];
});
