export default defineEventHandler((event) => {
  return [
    {
      number: 19,
      nkjv: "This <i>is</i> the genealogy of Isaac, Abraham's son. Abraham begot Isaac.",
      esv: "These are the generations of Isaac, Abraham's son: Abraham fathered Isaac,",
      csb: "These are the family records of Isaac son of Abraham. Abraham fathered Isaac.",
      net: "This is the account of Isaac, the son of Abraham. Abraham became the father of Isaac.",
      nlt: "This is the account of the family of Isaac, the son of Abraham.",
    },
    {
      number: 20,
      nkjv: "Isaac was forty years old when he took Rebekah as wife, the daughter of Bethuel the Syrian of Padan Aram, the sister of Laban the Syrian.",
      esv: "and Isaac was forty years old when he took Rebekah, the daughter of Bethuel the Aramean of Paddan-aram, the sister of Laban the Aramean, to be his wife.",
      csb: "Isaac was forty years old when he took as his wife Rebekah daughter of Bethuel the Aramean from Paddan-aram and sister of Laban the Aramean.",
      net: "When Isaac was forty years old, he married Rebekah, the daughter of Bethuel the Aramean from Paddan Aram and sister of Laban the Aramean.",
      nlt: "When Isaac was forty years old, he married Rebekah, the daughter of Bethuel the Aramean from Paddan-aram and the sister of Laban the Aramean.",
    },
    {
      number: 21,
      nkjv: "Now Isaac pleaded with the LORD for his wife, because she <i>was</i> barren; and the LORD granted his plea, and Rebekah his wife conceived.",
      esv: "And Isaac prayed to the LORD for his wife, because she was barren. And the LORD granted his prayer, and Rebekah his wife conceived.",
      csb: "Isaac prayed to the LORD on behalf of his wife because she was childless. The LORD was receptive to his prayer, and his wife Rebekah conceived.",
      net: "Isaac prayed to the LORD on behalf of his wife because she was childless. The LORD answered his prayer, and his wife Rebekah became pregnant.",
      nlt: "Isaac pleaded with the LORD on behalf of his wife, because she was unable to have children. The LORD answered Isaac's prayer, and Rebekah became pregnant with twins.",
    },
    {
      number: 22,
      nkjv: 'But the children struggled together within her; and she said, "If <i>all is</i> well, why <i>am I like</i> this?" So she went to inquire of the LORD.',
      esv: 'The children struggled together within her, and she said, "If it is thus, why is this happening to me?" So she went to inquire of the LORD.',
      csb: 'But the children inside her struggled with each other, and she said, "Why is this happening to me?" So she went to inquire of the LORD.',
      net: 'But the children struggled inside her, and she said, "If it is going to be like this, I\'m not so sure I want to be pregnant!" So she asked the LORD,',
      nlt: 'But the two children struggled with each other in her womb. So she went to ask the LORD about it. "Why is this happening to me?" she asked.',
    },
    {
      number: 23,
      nkjv: 'And the LORD said to her: "Two nations <i>are</i> in your womb, Two peoples shall be separated from your body; <i>One</i> people shall be stronger than the other, And the older shall serve the younger."',
      esv: 'And the LORD said to her, "Two nations are in your womb, and two peoples from within you shall be divided; the one shall be stronger than the other, the older shall serve the younger."',
      csb: "And the LORD said to her: Two nations are in your womb; two peoples will come from you and be separated. One people will be stronger than the other, and the older will serve the younger.",
      net: 'and the LORD said to her, "Two nations are in your womb, and two peoples will be separated from within you. One people will be stronger than the other, and the older will serve the younger."',
      nlt: 'And the LORD told her, "The sons in your womb will become two nations. From the very beginning, the two nations will be rivals. One nation will be stronger than the other; and your older son will serve your younger son."',
    },
    {
      number: 24,
      nkjv: "So when her days were fulfilled <i>for her</i> to give birth, indeed <i>there were</i> twins in her womb.",
      esv: "When her days to give birth were completed, behold, there were twins in her womb.",
      csb: "When her time came to give birth, there were indeed twins in her womb.",
      net: "When the time came for Rebekah to give birth, there were twins in her womb.",
      nlt: "And when the time came to give birth, Rebekah discovered that she did indeed have twins!",
    },
    {
      number: 25,
      nkjv: "And the first came out red. <i>He was</i> like a hairy garment all over; so they called his name Esau.",
      esv: "The first came out red, all his body like a hairy cloak, so they called his name Esau.",
      csb: "The first one came out red-looking, covered with hair like a fur coat, and they named him Esau.",
      net: "The first came out reddish all over, like a hairy garment, so they named him Esau.",
      nlt: "The first one was very red at birth and covered with thick hair like a fur coat. So they named him Esau.",
    },
    {
      number: 26,
      nkjv: "Afterward his brother came out, and his hand took hold of Esau's heel; so his name was called Jacob. Isaac <i>was</i> sixty years old when she bore them.",
      esv: "Afterward his brother came out with his hand holding Esau's heel, so his name was called Jacob. Isaac was sixty years old when she bore them.",
      csb: "After this, his brother came out grasping Esau's heel with his hand. So he was named Jacob. Isaac was sixty years old when they were born.",
      net: "When his brother came out with his hand clutching Esau's heel, they named him Jacob. Isaac was sixty years old when they were born.",
      nlt: "Then the other twin was born with his hand grasping Esau's heel. So they named him Jacob. Isaac was sixty years old when the twins were born.",
    },
    {
      number: 27,
      nkjv: "So the boys grew. And Esau was a skillful hunter, a man of the field; but Jacob was a mild man, dwelling in tents.",
      esv: "When the boys grew up, Esau was a skillful hunter, a man of the field, while Jacob was a quiet man, dwelling in tents.",
      csb: "When the boys grew up, Esau became an expert hunter, an outdoorsman, but Jacob was a quiet man who stayed at home.",
      net: "When the boys grew up, Esau became a skilled hunter, a man of the open fields, but Jacob was an even-tempered man, living in tents.",
      nlt: "As the boys grew up, Esau became a skillful hunter. He was an outdoorsman, but Jacob had a quiet temperament, preferring to stay at home.",
    },
    {
      number: 28,
      nkjv: "And Isaac loved Esau because he ate <i>of his</i> game, but Rebekah loved Jacob.",
      esv: "Isaac loved Esau because he ate of his game, but Rebekah loved Jacob.",
      csb: "Isaac loved Esau because he had a taste for wild game, but Rebekah loved Jacob.",
      net: "Isaac loved Esau because he had a taste for fresh game, but Rebekah loved Jacob.",
      nlt: "Isaac loved Esau because he enjoyed eating the wild game Esau brought home, but Rebekah loved Jacob.",
    },
    {
      number: 29,
      nkjv: "Now Jacob cooked a stew; and Esau came in from the field, and he <i>was</i> weary.",
      esv: "Once when Jacob was cooking stew, Esau came in from the field, and he was exhausted.",
      csb: "Once when Jacob was cooking a stew, Esau came in from the field exhausted.",
      net: "Now Jacob cooked some stew, and when Esau came in from the open fields, he was famished.",
      nlt: "One day when Jacob was cooking some stew, Esau arrived home from the wilderness exhausted and hungry.",
    },
    {
      number: 30,
      nkjv: 'And Esau said to Jacob, "Please feed me with that same red <i>stew</i>, for I <i>am</i> weary." Therefore his name was called Edom.',
      esv: 'And Esau said to Jacob, "Let me eat some of that red stew, for I am exhausted!" (Therefore his name was called Edom.)',
      csb: 'He said to Jacob, "Let me eat some of that red stuff, because I\'m exhausted." That is why he was also named Edom.',
      net: 'So Esau said to Jacob, "Feed me some of the red stuff - yes, this red stuff - because I\'m starving!" (That is why he was also called Edom.)',
      nlt: 'Esau said to Jacob, "I\'m starved! Give me some of that red stew!" (This is how Esau got his other name, Edom, which means "red.")',
    },
    {
      number: 31,
      nkjv: 'But Jacob said, "Sell me your birthright as of this day."',
      esv: 'Jacob said, "Sell me your birthright now."',
      csb: 'Jacob replied, "First sell me your birthright."',
      net: 'But Jacob replied, "First sell me your birthright."',
      nlt: '"All right," Jacob replied, "but trade me your rights as the firstborn son."',
    },
    {
      number: 32,
      nkjv: 'And Esau said, "Look, I <i>am</i> about to die; so what <i>is</i> this birthright to me?"',
      esv: 'Esau said, "I am about to die; of what use is a birthright to me?"',
      csb: '"Look," said Esau, "I\'m about to die, so what good is a birthright to me?"',
      net: '"Look," said Esau, "I\'m about to die! What use is the birthright to me?"',
      nlt: '"Look, I\'m dying of starvation!" said Esau. "What good is my birthright to me now?"',
    },
    {
      number: 33,
      nkjv: 'Then Jacob said, "Swear to me as of this day." So he swore to him, and sold his birthright to Jacob.',
      esv: 'Jacob said, "Swear to me now." So he swore to him and sold his birthright to Jacob.',
      csb: 'Jacob said, "Swear to me first." So he swore to Jacob and sold his birthright to him.',
      net: 'But Jacob said, "Swear an oath to me now." So Esau swore an oath to him and sold his birthright to Jacob.',
      nlt: 'But Jacob said, "First you must swear that your birthright is mine." So Esau swore an oath, thereby selling all his rights as the firstborn to his brother, Jacob.',
    },
    {
      number: 34,
      nkjv: "And Jacob gave Esau bread and stew of lentils; then he ate and drank, arose, and went his way. Thus Esau despised <i>his</i> birthright.",
      esv: "Then Jacob gave Esau bread and lentil stew, and he ate and drank and rose and went his way. Thus Esau despised his birthright.",
      csb: "Then Jacob gave bread and lentil stew to Esau; he ate, drank, got up, and went away. So Esau despised his birthright.",
      net: "Then Jacob gave Esau some bread and lentil stew; Esau ate and drank, then got up and went out. So Esau despised his birthright.",
      nlt: "Then Jacob gave Esau some bread and lentil stew. Esau ate the meal, then got up and left. He showed contempt for his rights as the firstborn.",
    },
  ];
});
