export default defineEventHandler((event) => {
  return {
    22: {
      kjv: "And he rose up that night, and took his two wives, and his two womenservants, and his eleven sons, and passed over the ford Jabbok.",
      niv: "That night Jacob got up and took his two wives, his two female servants and his eleven sons and crossed the ford of the Jabbok.",
      nkjv: "And he arose that night and took his two wives, his two female servants, and his eleven sons, and crossed over the ford of Jabbok.",
      esv: "The same night he arose and took his two wives, his two female servants, and his eleven children, and crossed the ford of the Jabbok.",
      csb: "During the night Jacob got up and took his two wives, his two slave women, and his eleven sons, and crossed the ford of Jabbok.",
      net: "During the night Jacob quickly took his two wives, his two female servants, and his eleven sons and crossed the ford of the Jabbok.",
      nlt: "During the night Jacob got up and took his two wives, his two servant wives, and his eleven sons and crossed the Jabbok River with them.",
    },
    23: {
      kjv: "And he took them, and sent them over the brook, and sent over that he had.",
      niv: "After he had sent them across the stream, he sent over all his possessions.",
      nkjv: "He took them, sent them over the brook, and sent over what he had.",
      esv: "He took them and sent them across the stream, and everything else that he had.",
      csb: "He took them and sent them across the stream, along with all his possessions.",
      net: "He took them and sent them across the stream along with all his possessions.",
      nlt: "After taking them to the other side, he sent over all his possessions.",
    },
    24: {
      kjv: "And Jacob was left alone; and there wrestled a man with him until the breaking of the day.",
      niv: "So Jacob was left alone, and a man wrestled with him till daybreak.",
      nkjv: "Then Jacob was left alone; and a Man wrestled with him until the breaking of day.",
      esv: "And Jacob was left alone. And a man wrestled with him until the breaking of the day.",
      csb: "Jacob was left alone, and a man wrestled with him until daybreak.",
      net: "So Jacob was left alone. Then a man wrestled with him until daybreak.",
      nlt: "This left Jacob all alone in the camp, and a man came and wrestled with him until the dawn began to break.",
    },
    25: {
      kjv: "And when he saw that he prevailed not against him, he touched the hollow of his thigh; and the hollow of Jacob's thigh was out of joint, as he wrestled with him.",
      niv: "When the man saw that he could not overpower him, he touched the socket of Jacob's hip so that his hip was wrenched as he wrestled with the man.",
      nkjv: "Now when He saw that He did not prevail against him, He touched the socket of his hip; and the socket of Jacob's hip was out of joint as He wrestled with him.",
      esv: "When the man saw that he did not prevail against Jacob, he touched his hip socket, and Jacob's hip was put out of joint as he wrestled with him.",
      csb: "When the man saw that he could not defeat him, he struck Jacob's hip socket as they wrestled and dislocated his hip.",
      net: "When the man saw that he could not defeat Jacob, he struck the socket of his hip so the socket of Jacob's hip was dislocated while he wrestled with him.",
      nlt: "When the man saw that he would not win the match, he touched Jacob's hip and wrenched it out of its socket.",
    },
    26: {
      kjv: "And he said, Let me go, for the day breaketh. And he said, I will not let thee go, except thou bless me.",
      niv: 'Then the man said, "Let me go, for it is daybreak." But Jacob replied, "I will not let you go unless you bless me."',
      nkjv: 'And He said, "Let Me go, for the day breaks." But he said, "I will not let You go unless You bless me!"',
      esv: 'Then he said, "Let me go, for the day has broken." But Jacob said, "I will not let you go unless you bless me."',
      csb: 'Then he said to Jacob, "Let me go, for it is daybreak." But Jacob said, "I will not let you go unless you bless me."',
      net: 'Then the man said, "Let me go, for the dawn is breaking." "I will not let you go," Jacob replied, "unless you bless me."',
      nlt: 'Then the man said, "Let me go, for the dawn is breaking!" But Jacob said, "I will not let you go unless you bless me."',
    },
    27: {
      kjv: "And he said unto him, What <i>is</i> thy name? And he said, Jacob.",
      niv: 'The man asked him, "What is your name?" "Jacob," he answered.',
      nkjv: 'So He said to him, "What <i>is</i> your name?" He said, "Jacob."',
      esv: 'And he said to him, "What is your name?" And he said, "Jacob."',
      csb: '"What is your name?" the man asked. "Jacob," he replied.',
      net: 'The man asked him, "What is your name?" He answered, "Jacob."',
      nlt: '"What is your name?" the man asked. He replied, "Jacob."',
    },
    28: {
      kjv: "And he said, Thy name shall be called no more Jacob, but Israel: for as a prince hast thou power with God and with men, and hast prevailed.",
      niv: 'Then the man said, "Your name will no longer be Jacob, but Israel, because you have struggled with God and with humans and have overcome."',
      nkjv: 'And He said, "Your name shall no longer be called Jacob, but Israel; for you have struggled with God and with men, and have prevailed."',
      esv: 'Then he said, "Your name shall no longer be called Jacob, but Israel, for you have striven with God and with men, and have prevailed."',
      csb: '"Your name will no longer be Jacob," he said. "It will be Israel because you have struggled with God and with men and have prevailed."',
      net: '"No longer will your name be Jacob," the man told him, "but Israel, because you have fought with God and with men and have prevailed."',
      nlt: '"Your name will no longer be Jacob," the man told him. "From now on you will be called Israel, because you have fought with God and with men and have won."',
    },
    29: {
      kjv: "And Jacob asked <i>him</i>, and said, Tell <i>me</i>, I pray thee, thy name. And he said, Wherefore <i>is</i> it <i>that</i> thou dost ask after my name? And he blessed him there.",
      niv: 'Jacob said, "Please tell me your name." But he replied, "Why do you ask my name?" Then he blessed him there.',
      nkjv: 'Then Jacob asked, saying, "Tell <i>me</i> Your name, I pray." And He said, "Why <i>is</i> it <i>that</i> you ask about My name?" And He blessed him there.',
      esv: 'Then Jacob asked him, "Please tell me your name." But he said, "Why is it that you ask my name?" And there he blessed him.',
      csb: 'Then Jacob asked him, "Please tell me your name." But he answered, "Why do you ask my name?" And he blessed him there.',
      net: 'Then Jacob asked, "Please tell me your name." "Why do you ask my name?" the man replied. Then he blessed Jacob there.',
      nlt: '"Please tell me your name," Jacob said. "Why do you want to know my name?" the man replied. Then he blessed Jacob there.',
    },
    30: {
      kjv: "And Jacob called the name of the place Peniel: for I have seen God face to face, and my life is preserved.",
      niv: 'So Jacob called the place Peniel, saying, "It is because I saw God face to face, and yet my life was spared."',
      nkjv: 'So Jacob called the name of the place Peniel: "For I have seen God face to face, and my life is preserved."',
      esv: 'So Jacob called the name of the place Peniel, saying, "For I have seen God face to face, and yet my life has been delivered."',
      csb: 'Jacob then named the place Peniel, "For I have seen God face to face," he said, "yet my life has been spared."',
      net: 'So Jacob named the place Peniel, explaining, "Certainly I have seen God face to face and have survived."',
      nlt: 'Jacob named the place Peniel (which means "face of God"), for he said, "I have seen God face to face, yet my life has been spared."',
    },
    31: {
      kjv: "And as he passed over Penuel the sun rose upon him, and he halted upon his thigh.",
      niv: "The sun rose above him as he passed Peniel, and he was limping because of his hip.",
      nkjv: "Just as he crossed over Penuel the sun rose on him, and he limped on his hip.",
      esv: "The sun rose upon him as he passed Penuel, limping because of his hip.",
      csb: "The sun shone on him as he passed by Penuel -- limping because of his hip.",
      net: "The sun rose over him as he crossed over Penuel, but he was limping because of his hip.",
      nlt: "The sun was rising as Jacob left Peniel, and he was limping because of the injury to his hip.",
    },
    32: {
      kjv: "Therefore the children of Israel eat not <i>of</i> the sinew which shrank, which <i>is</i> upon the hollow of the thigh, unto this day: because he touched the hollow of Jacob's thigh in the sinew that shrank.",
      niv: "Therefore to this day the Israelites do not eat the tendon attached to the socket of the hip, because the socket of Jacob's hip was touched near the tendon.",
      nkjv: "Therefore to this day the children of Israel do not eat the muscle that shrank, which <i>is</i> on the hip socket, because He touched the socket of Jacob's hip in the muscle that shrank.",
      esv: "Therefore to this day the people of Israel do not eat the sinew of the thigh that is on the hip socket, because he touched the socket of Jacob's hip on the sinew of the thigh.",
      csb: "That is why, still today, the Israelites don't eat the thigh muscle that is at the hip socket: because he struck Jacob's hip socket at the thigh muscle.",
      net: "That is why to this day the Israelites do not eat the sinew which is attached to the socket of the hip, because he struck the socket of Jacob's hip near the attached sinew.",
      nlt: "(Even today the people of Israel don't eat the tendon near the hip socket because of what happened that night when the man strained the tendon of Jacob's hip.)",
    },
  };
});
