export default defineEventHandler((event) => {
  return [
    {
      number: 1,
      nkjv: "Then the children of Israel did evil in the sight of the LORD. So the LORD delivered them into the hand of Midian for seven years,",
      esv: "The people of Israel did what was evil in the sight of the LORD, and the LORD gave them into the hand of Midian seven years.",
      csb: "The Israelites did what was evil in the sight of the LORD. So the LORD handed them over to Midian seven years,",
      net: "The Israelites did evil in the LORD's sight, so the LORD turned them over to Midian for seven years.",
      nlt: "The Israelites did evil in the LORD's sight. So the LORD handed them over to the Midianites for seven years.",
    },
    {
      number: 2,
      nkjv: "and the hand of Midian prevailed against Israel. Because of the Midianites, the children of Israel made for themselves the dens, the caves, and the strongholds which <i>are</i> in the mountains.",
      esv: "And the hand of Midian overpowered Israel, and because of Midian the people of Israel made for themselves the dens that are in the mountains and the caves and the strongholds.",
      csb: "and they oppressed Israel. Because of Midian, the Israelites made hiding places for themselves in the mountains, caves, and strongholds.",
      net: "The Midianites overwhelmed Israel. Because of Midian the Israelites made shelters for themselves in the hills, as well as caves and strongholds.",
      nlt: "The Midianites were so cruel that the Israelites made hiding places for themselves in the mountains, caves, and strongholds.",
    },
    {
      number: 7,
      nkjv: "And it came to pass, when the children of Israel cried out to the LORD because of the Midianites,",
      esv: "When the people of Israel cried out to the LORD on account of the Midianites,",
      csb: "When the Israelites cried out to him because of Midian,",
      net: "When the Israelites cried out to the LORD for help because of Midian,",
      nlt: "When they cried out to the LORD because of Midian,",
    },
    {
      number: 8,
      nkjv: "that the LORD sent a prophet to the children of Israel, who said to them, \"Thus says the LORD God of Israel: 'I brought you up from Egypt and brought you out of the house of bondage;",
      esv: 'the LORD sent a prophet to the people of Israel. And he said to them, "Thus says the LORD, the God of Israel: I led you up from Egypt and brought you out of the house of slavery.',
      csb: "the LORD sent a prophet to them. He said to them, \"This is what the LORD God of Israel says: 'I brought you out of Egypt and out of the place of slavery.",
      net: "he sent a prophet to the Israelites. He said to them, \"This is what the LORD God of Israel says: 'I brought you up from Egypt and took you out of that place of slavery.",
      nlt: 'the LORD sent a prophet to the Israelites. He said, "This is what the LORD, the God of Israel, says: I brought you up out of slavery in Egypt.',
    },
    {
      number: 9,
      nkjv: "'and I delivered you out of the hand of the Egyptians and out of the hand of all who oppressed you, and drove them out before you and gave you their land.",
      esv: "And I delivered you from the hand of the Egyptians and from the hand of all who oppressed you, and drove them out before you and gave you their land.",
      csb: '"I rescued you from the power of Egypt and the power of all who oppressed you. I drove them out before you and gave you their land.',
      net: "I rescued you from Egypt's power and from the power of all who oppressed you. I drove them out before you and gave their land to you.",
      nlt: "I rescued you from the Egyptians and from all who oppressed you. I drove out your enemies and gave you their land.",
    },
    {
      number: 10,
      nkjv: '\'Also I said to you, "I <i>am</i> the LORD your God; do not fear the gods of the Amorites, in whose land you dwell." But you have not obeyed My voice.\'"',
      esv: "And I said to you, 'I am the LORD your God; you shall not fear the gods of the Amorites in whose land you dwell.' But you have not obeyed my voice.\"",
      csb: '"I said to you: I am the LORD your God. Do not fear the gods of the Amorites whose land you live in. But you did not obey me.\'"',
      net: 'I said to you, "I am the LORD your God! Do not worship the gods of the Amorites, in whose land you are now living!" But you have disobeyed me.\'"',
      nlt: "I told you, 'I am the LORD your God. You must not worship the gods of the Amorites, in whose land you now live.' But you have not listened to me.\"",
    },
    {
      number: 11,
      nkjv: "Now the Angel of the LORD came and sat under the terebinth tree which <i>was</i> in Ophrah, which <i>belonged</i> to Joash the Abiezrite, while his son Gideon threshed wheat in the winepress, in order to hide <i>it</i> from the Midianites.",
      esv: "Now the angel of the LORD came and sat under the terebinth at Ophrah, which belonged to Joash the Abiezrite, while his son Gideon was beating out wheat in the winepress to hide it from the Midianites.",
      csb: "The angel of the LORD came, and he sat under the oak that was in Ophrah, which belonged to Joash, the Abiezrite. His son Gideon was threshing wheat in the winepress in order to hide it from the Midianites.",
      net: "The LORD's angelic messenger came and sat down under the oak tree in Ophrah owned by Joash the Abiezrite. He arrived while Joash's son Gideon was threshing wheat in a winepress so he could hide it from the Midianites.",
      nlt: "Then the angel of the LORD came and sat beneath the great tree at Ophrah, which belonged to Joash of the clan of Abiezer. Gideon son of Joash was threshing wheat at the bottom of a winepress to hide the grain from the Midianites.",
    },
    {
      number: 12,
      nkjv: 'And the Angel of the LORD appeared to him, and said to him, "The LORD <i>is</i> with you, you mighty man of valor!"',
      esv: 'And the angel of the LORD appeared to him and said to him, "The LORD is with you, O mighty man of valor."',
      csb: 'Then the angel of the LORD appeared to him and said, "The LORD is with you, valiant warrior."',
      net: 'The LORD\'s messenger appeared and said to him, "The LORD is with you, courageous warrior!"',
      nlt: 'The angel of the LORD appeared to him and said, "Mighty hero, the LORD is with you!"',
    },
    {
      number: 13,
      nkjv: "Gideon said to Him, \"O my lord, if the LORD is with us, why then has all this happened to us? And where <i>are</i> all His miracles which our fathers told us about, saying, 'Did not the LORD bring us up from Egypt?' But now the LORD has forsaken us and delivered us into the hands of the Midianites.\"",
      esv: "And Gideon said to him, \"Please, my lord, if the LORD is with us, why then has all this happened to us? And where are all his wonderful deeds that our fathers recounted to us, saying, 'Did not the LORD bring us up from Egypt?' But now the LORD has forsaken us and given us into the hand of Midian.\"",
      csb: "Gideon said to him, \"Please, my lord, if the LORD is with us, why has all this happened? And where are all his wonders that our ancestors told us about? They said, 'Hasn't the LORD brought us out of Egypt? ' But now the LORD has abandoned us and handed us over to Midian.\"",
      net: "Gideon said to him, \"Pardon me, but if the LORD is with us, why has such disaster overtaken us? Where are all his miraculous deeds our ancestors told us about? They said, 'Did the LORD not bring us up from Egypt?' But now the LORD has abandoned us and handed us over to Midian.\"",
      nlt: '"Sir," Gideon replied, "if the LORD is with us, why has all this happened to us? And where are all the miracles our ancestors told us about? Didn\'t they say, \'The LORD brought us up out of Egypt\'? But now the LORD has abandoned us and handed us over to the Midianites."',
    },
    {
      number: 14,
      nkjv: 'Then the LORD turned to him and said, "Go in this might of yours, and you shall save Israel from the hand of the Midianites. Have I not sent you?"',
      esv: 'And the LORD turned to him and said, "Go in this might of yours and save Israel from the hand of Midian; do not I send you?"',
      csb: 'The LORD turned to him and said, "Go in the strength you have and deliver Israel from the grasp of Midian. I am sending you!"',
      net: 'Then the LORD himself turned to him and said, "You have the strength. Deliver Israel from the power of the Midianites! Have I not sent you?"',
      nlt: 'Then the LORD turned to him and said, "Go with the strength you have, and rescue Israel from the Midianites. I am sending you!"',
    },
    {
      number: 15,
      nkjv: 'So he said to Him, "O my Lord, how can I save Israel? Indeed my clan <i>is</i> the weakest in Manasseh, and I <i>am</i> the least in my father\'s house."',
      esv: 'And he said to him, "Please, Lord, how can I save Israel? Behold, my clan is the weakest in Manasseh, and I am the least in my father\'s house."',
      csb: 'He said to him, "Please, Lord, how can I deliver Israel? Look, my family is the weakest in Manasseh, and I am the youngest in my father\'s family."',
      net: 'Gideon said to him, "But Lord, how can I deliver Israel? Just look! My clan is the weakest in Manasseh, and I am the youngest in my family."',
      nlt: '"But Lord," Gideon replied, "how can I rescue Israel? My clan is the weakest in the whole tribe of Manasseh, and I am the least in my entire family!"',
    },
    {
      number: 16,
      nkjv: 'And the LORD said to him, "Surely I will be with you, and you shall defeat the Midianites as one man."',
      esv: 'And the LORD said to him, "But I will be with you, and you shall strike the Midianites as one man."',
      csb: '"But I will be with you," the LORD said to him. "You will strike Midian down as if it were one man."',
      net: 'The LORD said to him, "Ah, but I will be with you! You will strike down the whole Midianite army."',
      nlt: 'The LORD said to him, "I will be with you. And you will destroy the Midianites as if you were fighting against one man."',
    },
  ];
});
