export const exodus = {
  title: { en: "Exodus", he: "שמות", roma: "Shemot (Names)", el: "Έξοδος" },
  slug: "exodus",
  sbl: "exo",
  description:
    "The second book of Moses, in which God reveals his true name and delivers the Israelites out of slavery in Egypt.",
  readings: [
    {
      title: { en: "Shemot", he: "שמות" },
      start: { chapter: 1, verse: 1 },
      end: { chapter: 6, verse: 1 },
    },
    {
      title: { en: "Vaera", he: "וארא" },
      start: { chapter: 6, verse: 2 },
      end: { chapter: 9, verse: 35 },
    },
    {
      title: { en: "Bo", he: "בא" },
      start: { chapter: 10, verse: 1 },
      end: { chapter: 13, verse: 16 },
    },
    {
      title: { en: "Beshalach", he: "בשלח" },
      start: { chapter: 13, verse: 17 },
      end: { chapter: 17, verse: 16 },
    },
    {
      title: { en: "Yitro", he: "יתרו" },
      start: { chapter: 18, verse: 1 },
      end: { chapter: 20, verse: 26 },
    },
    {
      title: { en: "Mishpatim", he: "משפטים" },
      start: { chapter: 21, verse: 1 },
      end: { chapter: 24, verse: 18 },
    },
    {
      title: { en: "Terumah", he: "תרומה" },
      start: { chapter: 25, verse: 1 },
      end: { chapter: 27, verse: 19 },
    },
    {
      title: { en: "Tetzaveh", he: "תצוה" },
      start: { chapter: 27, verse: 20 },
      end: { chapter: 30, verse: 10 },
    },
    {
      title: { en: "Ki Tisa", he: "כי תשא" },
      start: { chapter: 30, verse: 11 },
      end: { chapter: 34, verse: 35 },
    },
    {
      title: { en: "Vayakhel", he: "ויקהל" },
      start: { chapter: 35, verse: 1 },
      end: { chapter: 38, verse: 20 },
    },
    {
      title: { en: "Pekudei", he: "פקודי" },
      start: { chapter: 38, verse: 21 },
      end: { chapter: 40, verse: 38 },
    },
  ],
  chapters: [
    {
      cjps: [
        "These are the names of the sons of Israel who came to Egypt with Jacob, each coming with his household:",
        "Reuben, Simeon, Levi, and Judah;",
        "Issachar, Zebulun, and Benjamin;",
        "Dan and Naphtali, Gad and Asher.",
        "The total number of persons that were of Jacob’s issue came to seventy, Joseph being already in Egypt.",
        "Joseph died, and all his brothers, and all that generation.",
        "But the Israelites were fertile and prolific; they multiplied and increased very greatly, so that the land was filled with them.",
        "A new king arose over Egypt who did not know Joseph.",
        "And he said to his people, “Look, the Israelite people are much too numerous for us.",
        'Let us deal shrewdly with them, so that they may not increase; otherwise in the event of war they may join our enemies in fighting against us and rise from the ground.”<sup class="footnote-marker">*</sup><i class="footnote"><b>rise from the ground </b>Meaning perhaps from their wretched condition, cf. Hos. 2.2; or “gain ascendancy over the country.” Others “get them up out of the land.”</i> ',
        'So they set taskmasters over them to oppress them with forced labor; and they built garrison cities<sup class="footnote-marker">*</sup><i class="footnote"><b>garrison cities </b>Others “store cities.”</i> for Pharaoh: Pithom and Raamses.',
        "But the more they were oppressed, the more they increased and spread out, so that the [Egyptians] came to dread the Israelites.",
        "The Egyptians ruthlessly imposed upon the Israelites",
        'the various labors that they made them perform. Ruthlessly<sup class="footnote-marker">*</sup><i class="footnote"><b>the various labors that they made them perform. Ruthlessly </b>Brought up from the end of the verse for clarity.</i> they made life bitter for them with harsh labor at mortar and bricks and with all sorts of tasks in the field.',
        "The king of Egypt spoke to the Hebrew midwives, one of whom was named Shiphrah and the other Puah,",
        'saying, “When you deliver the Hebrew women, look at the birthstool:<sup class="footnote-marker">*</sup><i class="footnote"><b>birthstool </b>More precisely, the brick or stone supports used by Egyptian women during childbirth.</i> if it is a boy, kill him; if it is a girl, let her live.”',
        "The midwives, fearing God, did not do as the king of Egypt had told them; they let the boys live.",
        "So the king of Egypt summoned the midwives and said to them, “Why have you done this thing, letting the boys live?”",
        "The midwives said to Pharaoh, “Because the Hebrew women are not like the Egyptian women: they are vigorous. Before the midwife can come to them, they have given birth.”",
        "And God dealt well with the midwives; and the people multiplied and increased greatly.",
        'And [God] established households<sup class="footnote-marker">*</sup><i class="footnote"><b>households </b>Meaning of Heb. <i>batim</i> uncertain.</i> for the midwives, because they feared God.',
        "Then Pharaoh charged all his people, saying, “Every boy that is born you shall throw into the Nile, but let every girl live.”",
      ],
      kjv: [
        "Now these [are] the names of the children of Israel, which came into Egypt; every man and his household came with Jacob.",
        "Reuben, Simeon, Levi, and Judah,",
        "Issachar, Zebulun, and Benjamin,",
        "Dan, and Naphtali, Gad, and Asher.",
        "And all the souls that came out of the loins of Jacob were seventy souls: for Joseph was in Egypt [already].",
        "And Joseph died, and all his brethren, and all that generation.",
        "And the children of Israel were fruitful, and increased abundantly, and multiplied, and waxed exceeding mighty; and the land was filled with them.",
        "Now there arose up a new king over Egypt, which knew not Joseph.",
        "And he said unto his people, Behold, the people of the children of Israel [are] more and mightier than we:",
        "Come on, let us deal wisely with them; lest they multiply, and it come to pass, that, when there falleth out any war, they join also unto our enemies, and fight against us, and [so] get them up out of the land.",
        "Therefore they did set over them taskmasters to afflict them with their burdens. And they built for Pharaoh treasure cities, Pithom and Raamses.",
        "But the more they afflicted them, the more they multiplied and grew. And they were grieved because of the children of Israel.",
        "And the Egyptians made the children of Israel to serve with rigour:",
        "And they made their lives bitter with hard bondage, in morter, and in brick, and in all manner of service in the field: all their service, wherein they made them serve, [was] with rigour.",
        "And the king of Egypt spake to the Hebrew midwives, of which the name of the one [was] Shiphrah, and the name of the other Puah:",
        "And he said, When ye do the office of a midwife to the Hebrew women, and see [them] upon the stools; if it [be] a son, then ye shall kill him: but if it [be] a daughter, then she shall live.",
        "But the midwives feared God, and did not as the king of Egypt commanded them, but saved the men children alive.",
        "And the king of Egypt called for the midwives, and said unto them, Why have ye done this thing, and have saved the men children alive?",
        "And the midwives said unto Pharaoh, Because the Hebrew women [are] not as the Egyptian women; for they [are] lively, and are delivered ere the midwives come in unto them.",
        "Therefore God dealt well with the midwives: and the people multiplied, and waxed very mighty.",
        "And it came to pass, because the midwives feared God, that he made them houses.",
        "And Pharaoh charged all his people, saying, Every son that is born ye shall cast into the river, and every daughter ye shall save alive.",
      ],
      wlc: [
        "וְאֵלֶּה שְׁמוֹת בְּנֵי יִשְׂרָאֵל הַבָּאִים מִצְרָיְמָה אֵת יַעֲקֹב אִישׁ וּבֵיתוֹ בָּאוּ׃",
        "רְאוּבֵן שִׁמְעוֹן לֵוִי וִיהוּדָה׃",
        "יִשָּׂשכָר זְבוּלֻן וּבְנְיָמִן׃",
        "דָּן וְנַפְתָּלִי גָּד וְאָשֵׁר׃",
        "וַיְהִי כָּל־נֶפֶשׁ יֹצְאֵי יֶרֶךְ־יַעֲקֹב שִׁבְעִים נָפֶשׁ וְיוֹסֵף הָיָה בְמִצְרָיִם׃",
        "וַיָּמָת יוֹסֵף וְכָל־אֶחָיו וְכֹל הַדּוֹר הַהוּא׃",
        "וּבְנֵי יִשְׂרָאֵל פָּרוּ וַיִּשְׁרְצוּ וַיִּרְבּוּ וַיַּעַצְמוּ בִּמְאֹד מְאֹד וַתִּמָּלֵא הָאָרֶץ אֹתָם׃ פ",
        "וַיָּקָם מֶלֶךְ־חָדָשׁ עַל־מִצְרָיִם אֲשֶׁר לֹא־יָדַע אֶת־יוֹסֵף׃",
        "וַיֹּאמֶר אֶל־עַמּוֹ הִנֵּה עַם בְּנֵי יִשְׂרָאֵל רַב וְעָצוּם מִמֶּנּוּ׃",
        "הָבָה נִתְחַכְּמָה לוֹ פֶּן־יִרְבֶּה וְהָיָה כִּי־תִקְרֶאנָה מִלְחָמָה וְנוֹסַף גַּם־הוּא עַל־שֹׂנְאֵינוּ וְנִלְחַם־בָּנוּ וְעָלָה מִן־הָאָרֶץ׃",
        "וַיָּשִׂימוּ עָלָיו שָׂרֵי מִסִּים לְמַעַן עַנֹּתוֹ בְּסִבְלֹתָם וַיִּבֶן עָרֵי מִסְכְּנוֹת לְפַרְעֹה אֶת־פִּתֹם וְאֶת־רַעַמְסֵס׃",
        "וְכַאֲשֶׁר יְעַנּוּ אֹתוֹ כֵּן יִרְבֶּה וְכֵן יִפְרֹץ וַיָּקֻצוּ מִפְּנֵי בְּנֵי יִשְׂרָאֵל׃",
        "וַיַּעֲבִדוּ מִצְרַיִם אֶת־בְּנֵי יִשְׂרָאֵל בְּפָרֶךְ׃",
        "וַיְמָרְרוּ אֶת־חַיֵּיהֶם בַּעֲבֹדָה קָשָׁה בְּחֹמֶר וּבִלְבֵנִים וּבְכָל־עֲבֹדָה בַּשָּׂדֶה אֵת כָּל־עֲבֹדָתָם אֲשֶׁר־עָבְדוּ בָהֶם בְּפָרֶךְ׃",
        "וַיֹּאמֶר מֶלֶךְ מִצְרַיִם לַמְיַלְּדֹת הָעִבְרִיֹּת אֲשֶׁר שֵׁם הָאַחַת שִׁפְרָה וְשֵׁם הַשֵּׁנִית פּוּעָה׃",
        "וַיֹּאמֶר בְּיַלֶּדְכֶן אֶת־הָעִבְרִיּוֹת וּרְאִיתֶן עַל־הָאָבְנָיִם אִם־בֵּן הוּא וַהֲמִתֶּן אֹתוֹ וְאִם־בַּת הִיא וָחָיָה׃",
        "וַתִּירֶאןָ הַמְיַלְּדֹת אֶת־הָאֱלֹהִים וְלֹא עָשׂוּ כַּאֲשֶׁר דִּבֶּר אֲלֵיהֶן מֶלֶךְ מִצְרָיִם וַתְּחַיֶּיןָ אֶת־הַיְלָדִים׃",
        "וַיִּקְרָא מֶלֶךְ־מִצְרַיִם לַמְיַלְּדֹת וַיֹּאמֶר לָהֶן מַדּוּעַ עֲשִׂיתֶן הַדָּבָר הַזֶּה וַתְּחַיֶּיןָ אֶת־הַיְלָדִים׃",
        "וַתֹּאמַרְןָ הַמְיַלְּדֹת אֶל־פַּרְעֹה כִּי לֹא כַנָּשִׁים הַמִּצְרִיֹּת הָעִבְרִיֹּת כִּי־חָיוֹת הֵנָּה בְּטֶרֶם תָּבוֹא אֲלֵהֶן הַמְיַלֶּדֶת וְיָלָדוּ׃",
        "וַיֵּיטֶב אֱלֹהִים לַמְיַלְּדֹת וַיִּרֶב הָעָם וַיַּעַצְמוּ מְאֹד׃",
        "וַיְהִי כִּי־יָרְאוּ הַמְיַלְּדֹת אֶת־הָאֱלֹהִים וַיַּעַשׂ לָהֶם בָּתִּים׃",
        "וַיְצַו פַּרְעֹה לְכָל־עַמּוֹ לֵאמֹר כָּל־הַבֵּן הַיִּלּוֹד הַיְאֹרָה תַּשְׁלִיכֻהוּ וְכָל־הַבַּת תְּחַיּוּן׃ ס",
      ],
    },
  ],
};
