import type { Pentateuch, History, Wisdom, Prophets, Gospels, Acts, Epistles, Source } from "~/types";

export const OldTestament: Record<string, Pentateuch | History | Wisdom | Prophets> = {
  gen: 'Genesis',
  exo: 'Exodus',
  lev: 'Leviticus',
  num: 'Numbers',
  deu: 'Deuteronomy',
  jos: 'Joshua',
  jdg: 'Judges',
  rth: 'Ruth',
  '1sa': '1 Samuel',
  '2sa': '2 Samuel',
  '1ki': '1 Kings',
  '2ki': '2 Kings',
  '1ch': '1 Chronicles',
  '2ch': '2 Chronicles',
  ezr: 'Ezra',
  neh: 'Nehemiah',
  est: 'Esther',
  job: 'Job',
  psa: 'Psalms',
  pro: 'Proverbs',
  ecc: 'Ecclesiastes',
  sng: 'Song of Songs',
  isa: 'Isaiah',
  jer: 'Jeremiah',
  lam: 'Lamentations',
  eze: 'Ezekiel',
  dan: 'Daniel',
  hos: 'Hosea',
  joe: 'Joel',
  amo: 'Amos',
  oba: 'Obadiah',
  jon: 'Johanh',
  mic: 'Micah',
  nah: 'Nahum',
  hab: 'Habakkuk',
  zep: 'Zephaniah',
  hag: 'Haggai',
  zec: 'Zechariah',
  mal: 'Malachi',
}

export const NewTestament: Record<string, Gospels | Acts | Epistles> = {
  mat: 'Matthew',
  mar: 'Mark',
  luk: 'Luke',
  jhn: 'John',
  act: 'Acts',
  rom: 'Romans',
  '1co': '1 Corinthians',
  '2co': '2 Corinthians',
  gal: 'Galatians',
  eph: 'Ephesians',
  phl: 'Philippians',
  col: 'Colossians',
  '1th': '1 Thessalonians',
  '2th': '2 Thessalonians',
  '1ti': '1 Timothy',
  '2ti': '2 Timothy',
  tit: 'Titus',
  phm: 'Philemon',
  heb: 'Hebrews',
  jas: 'James',
  '1pe': '1 Peter',
  '2pe': '2 Peter',
  '1jo': '1 John',
  '2jo': '2 John',
  '3jo': '3 John',
  jde: 'Jude',
  rev: 'Revelation',
}

export const Sources: Record<Source, string> = {
  nasb20: 'New American Standard Bible (NASB), 2020',
  amp: 'Amplified Bible (AMP)',
  esv: 'English Standard Version (ESV)',
  kjv: 'King James Version (KJV)',
  nkjv: 'New King James Version (NKJV)',
  jps85: 'Jewish Publication Society (JPS), 1985',
  csb: 'Christian Standard Bible (CSB)',
  niv: 'New International Version (NIV)',
  nlt: 'New Living Translation (NLT)',
  heb: 'Masoretic Text',
  lxx: 'Septuagint (LXX)',
}