import type { Scripture } from "~/types"

export default [
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 1, text: 'Now these are the names of the sons of Israel who came to Egypt with Jacob; each came with his household:' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 2, text: 'Reuben, Simeon, Levi, and Judah;' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 3, text: 'Issachar, Zebulun, and Benjamin;' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 4, text: 'Dan and Naphtali, Gad, and Asher.' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 5, text: 'All the descendants of Jacob were seventy people; Joseph was [already] in Egypt.' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 6, text: 'Then Joseph died, and all his brothers and all that generation,' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 7, text: 'but the Israelites were prolific and increased greatly; they multiplied and became extremely strong, so that the land was filled with them.' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 8, text: 'Now a new king arose over Egypt, who did not know Joseph [nor the history of his accomplishments].' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 9, text: 'He said to his people, "Behold, the people of the sons of Israel are too many and too mighty for us [they greatly outnumber us].' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 10, text: '"Come, let us deal shrewdly with them, so that they will not multiply and in the event of war, join our enemies, and fight against us and escape from the land."' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 11, text: 'So they set taskmasters over them to oppress them with hard labor. And the sons of Israel built Pithom and Raamses as storage cities for Pharaoh.' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 12, text: 'But the more the Egyptians oppressed them, the more they multiplied and expanded, so that the Egyptians dreaded and were exasperated by the Israelites.' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 13, text: 'And the Egyptians made the Israelites serve rigorously [forcing them into severe slavery].' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 14, text: 'They made their lives bitter with hard labor in mortar, brick, and all kinds of field work. All their labor was harsh and severe.' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 15, text: 'Then the king of Egypt said to the Hebrew midwives, one of whom was named Shiphrah (beauty) and the other named Puah (splendor),' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 16, text: '"When you act as midwives to the Hebrew women and see them on the birthstool, if it is a son, you shall kill him; but if it is a daughter, she shall live."' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 17, text: 'But the midwives feared God [with profound reverence] and did not do as the king of Egypt commanded, but they let the boy babies live.' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 18, text: 'So the king of Egypt called for the midwives and said to them, "Why have you done this thing, and allowed the boy babies to live?"' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 19, text: 'The midwives answered Pharaoh, "Because the Hebrew women are not like the Egyptian women; they are vigorous and give birth quickly and their babies are born before the midwife can get to them."' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 20, text: 'So God was good to the midwives, and the people [of Israel] multiplied and became very strong.' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 21, text: 'And because the midwives feared God [with profound reverence], He established families and households for them.' },
    { source: 'amp', book: 'Exodus', chapter: 1, verse: 22, text: 'Then Pharaoh commanded all his people, saying, "Every son who is born [to the Hebrews] must be thrown into the Nile, but every daughter you shall keep alive."' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 1, text: 'Now a man of the house of Levi [the priestly tribe] went and took as his wife a daughter of Levi.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 2, text: 'The woman conceived and gave birth to a son; and when she saw that he was [especially] beautiful and healthy, she hid him for three months [to protect him from the Egyptians].' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 3, text: 'When she could no longer hide him, she got him a basket (chest) made of papyrus reeds and covered it with tar and pitch [making it waterproof]. Then she put the child in it and set it among the reeds by the bank of the Nile.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 4, text: 'And his sister [Miriam] stood some distance away to find out what would happen to him.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 5, text: 'Now the daughter of Pharaoh came down to bathe at the Nile, and [she, together with] her maidens walked along the river\'s bank; she saw the basket among the reeds and sent her maid [to get it], and she brought it to her.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 6, text: 'When she opened it, she saw the child, and behold, the baby was crying. And she took pity on him and said, "This is one of the Hebrews\' children."' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 7, text: 'Then his sister said to Pharaoh\'s daughter, "Shall I go and call a wet-nurse from the Hebrew women to nurse the child for you?"' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 8, text: 'And Pharaoh\'s daughter said to her, "Go ahead." So the girl went and called the child\'s mother.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 9, text: 'Then Pharaoh\'s daughter said to her, "Take this child away and nurse him for me, and I will give you your wages." So the woman took the child and nursed him.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 10, text: 'And the child grew, and she brought him to Pharaoh\'s daughter and he became her son. And she named him Moses, and said, "Because I drew him out of the water."' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 11, text: 'One day, after Moses had grown [into adulthood], it happened that he went to his countrymen and looked [with compassion] at their hard labors; and he saw an Egyptian beating a Hebrew, one of his countrymen.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 12, text: 'He turned to look around, and seeing no one, he killed the Egyptian and hid him in the sand.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 13, text: 'He went out the next day and saw two Hebrew men fighting with each other; and he said to the aggressor, "Why are you striking your friend?"' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 14, text: 'But the man said, "Who made you a prince and a judge over us? Do you intend to kill me as you killed the Egyptian?" Then Moses was afraid and said, "Certainly this incident is known."' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 15, text: 'When Pharaoh heard about this matter, he tried to kill Moses. Then Moses fled from Pharaoh\'s presence and took refuge in the land of Midian, where he sat down by a well.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 16, text: 'Now the priest of Midian had seven daughters; and they came and drew water [from the well where Moses was resting] and filled the troughs to water their father\'s flock.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 17, text: 'Then shepherds came and drove them away, but Moses stood up and helped them and watered their flock.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 18, text: 'When they came to Reuel (Jethro) their father, he said, "How is it that you have come back so soon today?"' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 19, text: 'They said, "An Egyptian saved us from the shepherds. He even drew water [from the well] for us and watered the flock."' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 20, text: 'Then he said to his daughters, "Where is he? Why have you left the man behind? Invite him to have something to eat."' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 21, text: 'Moses was willing to remain with the man, and he gave Moses his daughter Zipporah [to be his wife].' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 22, text: 'She gave birth to a son, and he named him Gershom (stranger); for he said, "I have been a stranger in a foreign land."' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 23, text: 'Now it happened after a long time [about forty years] that the king of Egypt died. And the children of Israel (Jacob) groaned and sighed because of the bondage, and they cried out. And their cry for help because of their bondage ascended to God.' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 24, text: 'So God heard their groaning and God remembered His covenant with Abraham, Isaac, and Jacob (Israel).' },
    { source: 'amp', book: 'Exodus', chapter: 2, verse: 25, text: 'God saw the sons of Israel, and God took notice [of them] and was concerned about them [knowing all, understanding all, remembering all].' },
] as Scripture[]