import type { Scripture } from "~/types"

export default [
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 1, text: 'Now these [are] the names of the children of Israel, which came into Egypt; every man and his household came with Jacob.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 2, text: 'Reuben, Simeon, Levi, and Judah,' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 3, text: 'Issachar, Zebulun, and Benjamin,' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 4, text: 'Dan, and Naphtali, Gad, and Asher.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 5, text: 'And all the souls that came out of the loins of Jacob were seventy souls: for Joseph was in Egypt [already].' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 6, text: 'And Joseph died, and all his brethren, and all that generation.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 7, text: 'And the children of Israel were fruitful, and increased abundantly, and multiplied, and waxed exceeding mighty; and the land was filled with them.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 8, text: 'Now there arose up a new king over Egypt, which knew not Joseph.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 9, text: 'And he said unto his people, Behold, the people of the children of Israel [are] more and mightier than we:' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 10, text: 'Come on, let us deal wisely with them; lest they multiply, and it come to pass, that, when there falleth out any war, they join also unto our enemies, and fight against us, and [so] get them up out of the land.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 11, text: 'Therefore they did set over them taskmasters to afflict them with their burdens. And they built for Pharaoh treasure cities, Pithom and Raamses.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 12, text: 'But the more they afflicted them, the more they multiplied and grew. And they were grieved because of the children of Israel.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 13, text: 'And the Egyptians made the children of Israel to serve with rigour:' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 14, text: 'And they made their lives bitter with hard bondage, in morter, and in brick, and in all manner of service in the field: all their service, wherein they made them serve, [was] with rigour.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 15, text: 'And the king of Egypt spake to the Hebrew midwives, of which the name of the one [was] Shiphrah, and the name of the other Puah:' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 16, text: 'And he said, When ye do the office of a midwife to the Hebrew women, and see [them] upon the stools; if it [be] a son, then ye shall kill him: but if it [be] a daughter, then she shall live.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 17, text: 'But the midwives feared God, and did not as the king of Egypt commanded them, but saved the men children alive.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 18, text: 'And the king of Egypt called for the midwives, and said unto them, Why have ye done this thing, and have saved the men children alive?' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 19, text: 'And the midwives said unto Pharaoh, Because the Hebrew women [are] not as the Egyptian women; for they [are] lively, and are delivered ere the midwives come in unto them.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 20, text: 'Therefore God dealt well with the midwives: and the people multiplied, and waxed very mighty.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 21, text: 'And it came to pass, because the midwives feared God, that he made them houses.' },
    { source: 'kjv', book: 'Exodus', chapter: 1, verse: 22, text: 'And Pharaoh charged all his people, saying, Every son that is born ye shall cast into the river, and every daughter ye shall save alive.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 1, text: 'And there went a man of the house of Levi, and took [to wife] a daughter of Levi.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 2, text: 'And the woman conceived, and bare a son: and when she saw him that he [was a] goodly [child], she hid him three months.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 3, text: 'And when she could not longer hide him, she took for him an ark of bulrushes, and daubed it with slime and with pitch, and put the child therein; and she laid [it] in the flags by the river\'s brink.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 4, text: 'And his sister stood afar off, to wit what would be done to him.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 5, text: 'And the daughter of Pharaoh came down to wash [herself] at the river; and her maidens walked along by the river\'s side; and when she saw the ark among the flags, she sent her maid to fetch it.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 6, text: 'And when she had opened [it], she saw the child: and, behold, the babe wept. And she had compassion on him, and said, This [is one] of the Hebrews\' children.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 7, text: 'Then said his sister to Pharaoh\'s daughter, Shall I go and call to thee a nurse of the Hebrew women, that she may nurse the child for thee?' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 8, text: 'And Pharaoh\'s daughter said to her, Go. And the maid went and called the child\'s mother.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 9, text: 'And Pharaoh\'s daughter said unto her, Take this child away, and nurse it for me, and I will give [thee] thy wages. And the woman took the child, and nursed it.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 10, text: 'And the child grew, and she brought him unto Pharaoh\'s daughter, and he became her son. And she called his name Moses: and she said, Because I drew him out of the water.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 11, text: 'And it came to pass in those days, when Moses was grown, that he went out unto his brethren, and looked on their burdens: and he spied an Egyptian smiting an Hebrew, one of his brethren.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 12, text: 'And he looked this way and that way, and when he saw that [there was] no man, he slew the Egyptian, and hid him in the sand.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 13, text: 'And when he went out the second day, behold, two men of the Hebrews strove together: and he said to him that did the wrong, Wherefore smitest thou thy fellow?' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 14, text: 'And he said, Who made thee a prince and a judge over us? intendest thou to kill me, as thou killedst the Egyptian? And Moses feared, and said, Surely this thing is known.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 15, text: 'Now when Pharaoh heard this thing, he sought to slay Moses. But Moses fled from the face of Pharaoh, and dwelt in the land of Midian: and he sat down by a well.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 16, text: 'Now the priest of Midian had seven daughters: and they came and drew [water], and filled the troughs to water their father\'s flock.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 17, text: 'And the shepherds came and drove them away: but Moses stood up and helped them, and watered their flock.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 18, text: 'And when they came to Reuel their father, he said, How [is it that] ye are come so soon to day?' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 19, text: 'And they said, An Egyptian delivered us out of the hand of the shepherds, and also drew [water] enough for us, and watered the flock.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 20, text: 'And he said unto his daughters, And where [is] he? why [is] it [that] ye have left the man? call him, that he may eat bread.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 21, text: 'And Moses was content to dwell with the man: and he gave Moses Zipporah his daughter.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 22, text: 'And she bare [him] a son, and he called his name Gershom: for he said, I have been a stranger in a strange land.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 23, text: 'And it came to pass in process of time, that the king of Egypt died: and the children of Israel sighed by reason of the bondage, and they cried, and their cry came up unto God by reason of the bondage.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 24, text: 'And God heard their groaning, and God remembered his covenant with Abraham, with Isaac, and with Jacob.' },
    { source: 'kjv', book: 'Exodus', chapter: 2, verse: 25, text: 'And God looked upon the children of Israel, and God had respect unto [them].' },
] as Scripture[]