import type { Scripture } from "~/types"

export default [
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:1,  text: 'Now these are the names of the sons of Israel who came to Egypt with Jacob; they came, each one with his household:' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:2,  text: 'Reuben, Simeon, Levi, and Judah;' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:3,  text: 'Issachar, Zebulun, and Benjamin;' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:4,  text: 'Dan and Naphtali, Gad and Asher.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:5,  text: 'All the people who descended from Jacob were seventy people, but Joseph was [already] in Egypt.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:6,  text: 'And Joseph died, and all his brothers and all that generation.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:7,  text: 'But the sons of Israel were fruitful and increased greatly, and multiplied, and became exceedingly mighty, so that the land was filled with them.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:8,  text: 'Now a new king arose over Egypt, who did not know Joseph.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:9,  text: 'And he said to his people, "Behold, the people of the sons of Israel are too many and too mighty for us.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:10, text: '"Come, let us deal shrewdly with them, otherwise they will multiply, and in the event of war, they will also join those who hate us, and fight against us and depart from the land."' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:11, text: 'So they appointed taskmasters over them to oppress them with hard labor. And they built for Pharaoh storage cities, Pithom and Raamses.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:12, text: 'But the more they oppressed them, the more they multiplied and the more they spread out, so that they dreaded the sons of Israel.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:13, text: 'The Egyptians used violence to compel the sons of Israel to labor;' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:14, text: 'and they made their lives bitter with hard labor in mortar and bricks and at all [kinds of] labor in the field, all their labors which they violently had them perform as slaves.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:15, text: 'Then the king of Egypt spoke to the Hebrew midwives, one of whom was named Shiphrah, and the other was named Puah;' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:16, text: 'and he said, "When you are helping the Hebrew women to give birth and see [them] upon the birthstool, if it is a son, then you shall put him to death; but if it is a daughter, then she shall live."' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:17, text: 'But the midwives feared God, and did not do as the king of Egypt had commanded them, but let the boys live.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:18, text: 'So the king of Egypt called for the midwives and said to them, "Why have you done this thing, and let the boys live?"' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:19, text: 'The midwives said to Pharaoh, "Because the Hebrew women are not like the Egyptian women; for they are vigorous and give birth before the midwife can get to them."' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:20, text: 'So God was good to the midwives, and the people multiplied, and became very mighty.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:21, text: 'And because the midwives feared God, He established households for them.' },
    { source: 'nasb20', book: 'Exodus', chapter: 1, verse:22, text: 'Then Pharaoh commanded all his people, saying, "Every son who is born, you are to throw into the Nile, but every daughter, you are to keep alive."' },

    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 1,  text: 'Now a man from the house of Levi went and married a daughter of Levi.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 2,  text: 'And the woman conceived and gave birth to a son; and when she saw that he was beautiful, she hid him for three months.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 3,  text: 'But when she could no longer hide him, she got him a papyrus basket and covered it with tar and pitch. Then she put the child in it and set [it] among the reeds by the bank of the Nile.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 4,  text: 'And his sister stood at a distance to find out what would happen to him.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 5,  text: 'Now the daughter of Pharaoh came down to bathe at the Nile, with her female attendants walking alongside the Nile; and she saw the basket among the reeds and sent her slave woman, and she brought it [to her.]' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 6,  text: 'When she opened [it,] she saw the child, and behold, [the] boy was crying. And she had pity on him and said, "This is one of the Hebrews\' children."' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 7,  text: 'Then his sister said to Pharaoh\'s daughter, "Shall I go and call a woman for you who is nursing from the Hebrew women, so that she may nurse the child for you?"' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 8,  text: 'Pharaoh\'s daughter said to her, "Go [ahead.]" So the girl went and called the child\'s mother.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 9,  text: 'Then Pharaoh\'s daughter said to her, "Take this child away and nurse him for me, and I will give [you] your wages." So the woman took the child and nursed him.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 10, text: 'And the child grew, and she brought him to Pharaoh\'s daughter and he became her son. And she named him Moses, and said, "Because I drew him out of the water."' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 11, text: 'Now it came about in those days, when Moses had grown up, that he went out to his fellow Hebrews and looked at their hard labors; and he saw an Egyptian beating a Hebrew, one of his fellow Hebrews.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 12, text: 'So he looked this way and that, and when he saw that there was no one [around,] he struck and killed the Egyptian, and hid his body in the sand.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 13, text: 'Now he went out the next day, and behold, two Hebrews were fighting with each other; and he said to the offender, "Why are you striking your companion?"' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 14, text: 'But he said, "Who made you a ruler and a judge over us? Do you intend to kill me as you killed the Egyptian?" Then Moses was afraid and said, "Surely the matter has become known!"' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 15, text: 'When Pharaoh heard about this matter, he tried to kill Moses. But Moses fled from the presence of Pharaoh and settled in the land of Midian, and he sat down by a well.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 16, text: 'Now the priest of Midian had seven daughters; and they came to draw water and filled the troughs to water their father\'s flock.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 17, text: 'Then the shepherds came and drove them away, but Moses stood up and helped them and watered their flock.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 18, text: 'When they came to their father Reuel, he said, "Why have you come [back] so soon today?"' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 19, text: 'They said, "An Egyptian saved us from the shepherds, and what is more, he even drew water for us and watered the flock."' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 20, text: 'So he said to his daughters, "Where is he then? Why is it that you have left the man behind? Invite him to have something to eat."' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 21, text: 'And Moses was willing to live with the man. And he gave his daughter Zipporah to Moses.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 22, text: 'Then she gave birth to a son, and he named him Gershom, for he said, "I have been a stranger in a foreign land."' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 23, text: 'Now it came about in [the course of] those many days that the king of Egypt died. And the sons of Israel groaned because of the bondage, and they cried out; and their cry for help because of [their] bondage ascended to God.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 24, text: 'So God heard their groaning; and God remembered His covenant with Abraham, Isaac, and Jacob.' },
    { source: 'nasb20', book: 'Exodus', chapter: 2, verse: 25, text: 'And God saw the sons of Israel, and God took notice [of them.]' },
] as Scripture[]