import type { Scripture } from "~/types"

export default [
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 1, text: 'These are the names of the sons of Israel who went to Egypt with Jacob, each with his family:' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 2, text: 'Reuben, Simeon, Levi and Judah;' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 3, text: 'Issachar, Zebulun and Benjamin;' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 4, text: 'Dan and Naphtali; Gad and Asher.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 5, text: 'The descendants of Jacob numbered seventy in all; Joseph was already in Egypt.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 6, text: 'Now Joseph and all his brothers and all that generation died,' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 7, text: 'but the Israelites were exceedingly fruitful; they multiplied greatly, increased in numbers and became so numerous that the land was filled with them.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 8, text: 'Then a new king, to whom Joseph meant nothing, came to power in Egypt.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 9, text: '"Look," he said to his people, "the Israelites have become far too numerous for us.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 10, text: 'Come, we must deal shrewdly with them or they will become even more numerous and, if war breaks out, will join our enemies, fight against us and leave the country."' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 11, text: 'So they put slave masters over them to oppress them with forced labor, and they built Pithom and Rameses as store cities for Pharaoh.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 12, text: 'But the more they were oppressed, the more they multiplied and spread; so the Egyptians came to dread the Israelites' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 13, text: 'and worked them ruthlessly.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 14, text: 'They made their lives bitter with harsh labor in brick and mortar and with all kinds of work in the fields; in all their harsh labor the Egyptians worked them ruthlessly.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 15, text: 'The king of Egypt said to the Hebrew midwives, whose names were Shiphrah and Puah,' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 16, text: '"When you are helping the Hebrew women during childbirth on the delivery stool, if you see that the baby is a boy, kill him; but if it is a girl, let her live."' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 17, text: 'The midwives, however, feared God and did not do what the king of Egypt had told them to do; they let the boys live.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 18, text: 'Then the king of Egypt summoned the midwives and asked them, "Why have you done this? Why have you let the boys live?"' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 19, text: 'The midwives answered Pharaoh, "Hebrew women are not like Egyptian women; they are vigorous and give birth before the midwives arrive."' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 20, text: 'So God was kind to the midwives and the people increased and became even more numerous.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 21, text: 'And because the midwives feared God, he gave them families of their own.' },
    { source: 'niv', book: 'Exodus', chapter: 1, verse: 22, text: 'Then Pharaoh gave this order to all his people: "Every Hebrew boy that is born you must throw into the Nile, but let every girl live."' },

    { source: 'niv', book: 'Exodus', chapter: 2, verse: 1, text: 'Now a man of the tribe of Levi married a Levite woman,' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 2, text: 'and she became pregnant and gave birth to a son. When she saw that he was a fine child, she hid him for three months.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 3, text: 'But when she could hide him no longer, she got a papyrus basket for him and coated it with tar and pitch. Then she placed the child in it and put it among the reeds along the bank of the Nile.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 4, text: 'His sister stood at a distance to see what would happen to him.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 5, text: 'Then Pharaoh\'s daughter went down to the Nile to bathe, and her attendants were walking along the riverbank. She saw the basket among the reeds and sent her female slave to get it.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 6, text: 'She opened it and saw the baby. He was crying, and she felt sorry for him. "This is one of the Hebrew babies," she said.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 7, text: 'Then his sister asked Pharaoh\'s daughter, "Shall I go and get one of the Hebrew women to nurse the baby for you?"' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 8, text: '"Yes, go," she answered. So the girl went and got the baby\'s mother.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 9, text: 'Pharaoh\'s daughter said to her, "Take this baby and nurse him for me, and I will pay you." So the woman took the baby and nursed him.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 10, text: 'When the child grew older, she took him to Pharaoh\'s daughter and he became her son. She named him Moses, saying, "I drew him out of the water."' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 11, text: 'One day, after Moses had grown up, he went out to where his own people were and watched them at their hard labor. He saw an Egyptian beating a Hebrew, one of his own people.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 12, text: 'Looking this way and that and seeing no one, he killed the Egyptian and hid him in the sand.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 13, text: 'The next day he went out and saw two Hebrews fighting. He asked the one in the wrong, "Why are you hitting your fellow Hebrew?"' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 14, text: 'The man said, "Who made you ruler and judge over us? Are you thinking of killing me as you killed the Egyptian?" Then Moses was afraid and thought, "What I did must have become known."' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 15, text: 'When Pharaoh heard of this, he tried to kill Moses, but Moses fled from Pharaoh and went to live in Midian, where he sat down by a well.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 16, text: 'Now a priest of Midian had seven daughters, and they came to draw water and fill the troughs to water their father\'s flock.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 17, text: 'Some shepherds came along and drove them away, but Moses got up and came to their rescue and watered their flock.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 18, text: 'When the girls returned to Reuel their father, he asked them, "Why have you returned so early today?"' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 19, text: 'They answered, "An Egyptian rescued us from the shepherds. He even drew water for us and watered the flock."' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 20, text: '"And where is he?" Reuel asked his daughters. "Why did you leave him? Invite him to have something to eat."' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 21, text: 'Moses agreed to stay with the man, who gave his daughter Zipporah to Moses in marriage.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 22, text: 'Zipporah gave birth to a son, and Moses named him Gershom, saying, "I have become a foreigner in a foreign land."' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 23, text: 'During that long period, the king of Egypt died. The Israelites groaned in their slavery and cried out, and their cry for help because of their slavery went up to God.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 24, text: 'God heard their groaning and he remembered his covenant with Abraham, with Isaac and with Jacob.' },
    { source: 'niv', book: 'Exodus', chapter: 2, verse: 25, text: 'So God looked on the Israelites and was concerned about them.' },
] as Scripture[]